name: detekt lint

on:
  workflow_dispatch:

jobs:
  detekt:
    runs-on: ubuntu-latest

    steps:
      - name: Setup detekt
        uses: peter-murray/setup-detekt@v1
        with:
          detekt_version: 1.15.0

      - name: print current path
        run: pwd && ls

      - name: Run detekt
        run: detekt --version
